CCCEMContainerModObj.addLang('EN', 'english', {
    //cccem.js
    "Failed to save CCCEM settings": "Failed to save CCCEM settings",
    "Force close the game (or reload on web) to return to your save.": "Force close the game (or reload on web) to return to your save.",
    "Successfully found a %1": "Successfully found a %1",
    "Failed to find a %1": "Failed to find a %1",
    "Your seed is %1": "Your seed is %1",
    "FtHoF set": "FtHoF set",
    "Cast count (all time): %1": "Cast count (all time): %1",
    "Preloaded seeds loaded!": "Preloaded seeds loaded!",
    "Mod partially not loaded": "Mod partially not loaded",
    "Assets loads experienced a timeout. Try again later.": "Assets loads experienced a timeout. Try again later.",
    "Saving failed!": "Saving failed!",
    "Warning": "Warning",
    "You imported a settings code from an older version, which may cause some values to be set to bad values. Re-setting such values should usually fix the problem. Code version: %1; current version: %2.": "You imported a settings code from an older version, which may cause some values to be set to bad values. Re-setting such values should usually fix the problem. Code version: %1; current version: %2.",
    "Warning: outdated settings": "Warning: outdated settings",
    "The settings may not cover every setting. (current: %1, settings was created with: %2)<br>Export settings again to obtain an up-to-date setting.": "The settings may not cover every setting. (current: %1, settings was created with: %2)<br>Export settings again to obtain an up-to-date setting.",
    "Warning: outdated mod": "Warning: outdated mod",
    "The settings are made in a future version of the mod (current: %1, settings was created with: %2)": "The settings are made in a future version of the mod (current: %1, settings was created with: %2)",
    "Save overridden": "Save overridden",
    "Settings contained empty save": "Settings contained empty save",
    "CCCEM Settings load failed!": "CCCEM Settings load failed!",
    "Unknown load error (saved settings discarded)": "Unknown load error (saved settings discarded)",
    "Timeout waiting for prerequisite #%1": "Timeout waiting for prerequisite #%1",
    "CCCEM failed to load!": "CCCEM failed to load!",
    "Error: %1<br>Check your internet connection, and try remove adblockers.": "Error: %1<br>Check your internet connection, and try remove adblockers.",
    "CCCEM %1 Loaded!": "CCCEM %1 Loaded!",
    "Go to options to exit practice mode.": "Go to options to exit practice mode.",
    "Your save will return upon closing the game.": "Your save will return upon closing the game.",
    "Select a preset via hovering the button at top left, and customize it to your liking.": "Select a preset via hovering the button at top left, and customize it to your liking.",
    "Stored settings successfully loaded.": "Stored settings successfully loaded.",

    //cccemPresets.js nontrivial
    "Preset %1 set!": "Preset %1 set!",
    "Click \"Try again\" through the presets option category to restart practice or aim for higher scores.": "Click \"Try again\" through the presets option category to restart practice or aim for higher scores.",
    "Remove or edit the setting changes through the presets option category.": "Remove or edit the setting changes through the presets option category.",
    "Additional reminder": "Additional reminder",
    "Confirm preset": "Confirm preset",
    "You are about to apply the <b>%1</b> preset.": "You are about to apply the <b>%1</b> preset.",
    "Confirm preset (external!)": "Confirm preset (external!)",
    "Combo info": "Combo info",
    "The <b>Force the Hand of Fate</b> Grimoire spell has an unusually high chance of giving Click frenzy (x777 clicks). If you cast it during a Frenzy (x7 CpS) and get Click frenzy, sell buildings to the Godzamok pantheon god, then click as fast as you can to get <b>a lot of cookies</b>!": "The <b>Force the Hand of Fate</b> Grimoire spell has an unusually high chance of giving Click frenzy (x777 clicks). If you cast it during a Frenzy (x7 CpS) and get Click frenzy, sell buildings to the Godzamok pantheon god, then click as fast as you can to get <b>a lot of cookies</b>!",
    "What should I sell for Godzamok? A useful rule is to sell <b>every building</b> making less than <b>2%</b> of your total CpS. If you quickly sell multiple times you might see the buff not increase in strength, but <b>it\'s actually lying</b>; the buff does get stronger as shown if you try clicking the big cookie. In this case, you should sell from cursors all the way up to temples, but when you are actually doing it, you may need to sell more or less.": "What should I sell for Godzamok? A useful rule is to sell <b>every building</b> making less than <b>2%</b> of your total CpS. If you quickly sell multiple times you might see the buff not increase in strength, but <b>it\'s actually lying</b>; the buff does get stronger as shown if you try clicking the big cookie. In this case, you should sell from cursors all the way up to temples, but when you are actually doing it, you may need to sell more or less.",
    "In the preset the spell is being forced to give Click frenzy, but in reality you only have about a ~25% chance of getting it each attempt. Still, it remains an extremely powerful cookie-making strategy.": "In the preset the spell is being forced to give Click frenzy, but in reality you only have about a ~25% chance of getting it each attempt. Still, it remains an extremely powerful cookie-making strategy.",
    "Got it!": "Got it!",
    "Please wait...": "Please wait...",
    "Browse presets": "Browse presets",
    "Enter information below about your preset.": "Enter information below about your preset.",
    "Ingame name": "Ingame name",
    "Button description": "Button description",
    "Reminder to player": "Reminder to player",
    "Extended name": "Extended name",
    "Description": "Description",
    "Creator": "Creator",
    "<b>%1:</b> %2": "<b>%1:</b> %2",
    "Name displayed in the notification and tooltip when applying your preset. Keep it short.": "Name displayed in the notification and tooltip when applying your preset. Keep it short.",
    "A shortened version of the description for small tooltips. Displayed when hovering over the preset button. Keep it relatively short.": "A shortened version of the description for small tooltips. Displayed when hovering over the preset button. Keep it relatively short.",
    "Displayed on the confirmation prompt when applying the preset, and in the notification afterwards.": "Displayed on the confirmation prompt when applying the preset, and in the notification afterwards.",
    "Only displayed in the preset browser.": "Only displayed in the preset browser.",
    "Only displayed in the preset browser. Put information such as what it's for and how to use it in here. Up to 3000 characters.": "Only displayed in the preset browser. Put information such as what it's for and how to use it in here. Up to 3000 characters.",
    "Put your name here (or what you would like others to refer to you). Optional.": "Put your name here (or what you would like others to refer to you). Optional.",
    "Choose buttons that will be visible and modifiable when your preset is used.<br>Note: buttons are always inserted at the end of the list.": "Choose buttons that will be visible and modifiable when your preset is used.<br>Note: buttons are always inserted at the end of the list.",
    "Hidden": "Hidden",
    "Visible": "Visible",
    "Click an icon to select it. No selection yet.": "Click an icon to select it. No selection yet.",
    "Click on an icon to select it. Selected icon coordinates: <b>(%1, %2)</b>.": "Click on an icon to select it. Selected icon coordinates: <b>(%1, %2)</b>.",
    "Now, go to <a href=\"%1\" target=\"_blank\">this form</a> and input the below code!": "Now, go to <a href=\"%1\" target=\"_blank\">this form</a> and input the below code!",
    "The preset was successfully submitted.": "The preset was successfully submitted.",
    "Done!": "Done!",
    "Try it out": "Try it out",
    "Unnamed preset": "Unnamed preset",
    "By: %1": "By: %1",
    "(Open to see more)": "(Open to see more)",

    //cccemPresets.js enumerable
    "Basic combo": "Basic combo",
    "After finishing execution, click <b>Try again</b> in the menu to practice more or try for a higher score.<br>Check the Guide button for instructions.<br>For reliable execution, aim for <b>100% score</b> adjusted for <b>10 clicks/s</b>.": "After finishing execution, click <b>Try again</b> in the menu to practice more or try for a higher score.<br>Check the Guide button for instructions.<br>For reliable execution, aim for <b>100% score</b> adjusted for <b>10 clicks/s</b>.",
    "Grail": "Grail",
    "For reliable execution, aim for a score of at least <b>100%</b> adjusted for <b>10 clicks/s</b>.<br>Also note that this combo is almost exclusively for post-endgame (after all cookie-related achievements).": "For reliable execution, aim for a score of at least <b>100%</b> adjusted for <b>10 clicks/s</b>.<br>Also note that this combo is almost exclusively for post-endgame (after all cookie-related achievements).",
    "Consistency": "Consistency",
    "For reliable execution, aim for a score of at least <b>60%</b> adjusted for <b>10 clicks/s</b>.": "For reliable execution, aim for a score of at least <b>60%</b> adjusted for <b>10 clicks/s</b>.",
    "BS Scry": "BS Scry",
    "Setup combo": "Setup combo",
    "<b>Score greatly varies for the amount of cps boosters used</b>. For reliable execution, aim for a score of at least <b>100%</b> adjusted for <b>10 clicks/s</b> with mokal swap used.": "<b>Score greatly varies for the amount of cps boosters used</b>. For reliable execution, aim for a score of at least <b>100%</b> adjusted for <b>10 clicks/s</b> with mokal swap used.",
    "Initializing": "Initializing",

    //cccemInterface.js nontrivial
    "CCCEM interface": "CCCEM interface",
    "Combo history": "Combo history",
    "This is a list of your past combo attempts this session.": "This is a list of your past combo attempts this session.",
    "Get at least <b>%1</b> score from an attempt to be stored here. Press try again to end an attempt.": "Get at least <b>%1</b> score from an attempt to be stored here. Press try again to end an attempt.",
    "Go back": "Go back",
    "Open history settings": "Open history settings",
    "Unknown error": "Unknown error",
    "Stats displayed in reset notification": "Stats displayed in reset notification",
    "Stats displayed in history viewer": "Stats displayed in history viewer",
    "History settings failed to load!": "History settings failed to load!",
    "Duration: %1": "Duration: %1",
    "Stat": "Stat",
    "Stat description": "Stat description",
    "Score": "Score",
    "An evaluation of your execution in terms of skill displayed. Luck (such as how many buffs) do not factor into the calculations.": "An evaluation of your execution in terms of skill displayed. Luck (such as how many buffs) do not factor into the calculations.",
    "CpS gained": "CpS gained",
    "Amount of cookies in terms of CpS gained during the attempt.": "Amount of cookies in terms of CpS gained during the attempt.",
    "Strength of Godzamok": "Strength of Godzamok",
    "Maximum strength of the Devastation (Godzamok) buff.": "Maximum strength of the Devastation (Godzamok) buff.",
    "Clicks": "Clicks",
    "Estimated number of clicks useful in the attempt.": "Estimated number of clicks useful in the attempt.",
    "Devastatedness": "Devastatedness",
    "Maximum Godzamok power, multiplied by the amount of clicks during devastation.": "Maximum Godzamok power, multiplied by the amount of clicks during devastation.",
    "Rebuy multiplier": "Rebuy multiplier",
    "Multiplier contribution from rebuying behavior (if enabled).": "Multiplier contribution from rebuying behavior (if enabled).",
    "Combo strength": "Combo strength",
    "Maximum observed combo multiplier during the attempt.": "Maximum observed combo multiplier during the attempt.",
    "Strength of non-constant buffs": "Strength of non-constant buffs",
    "Cumulative strength of buffs that are not generally considered guaranteed.": "Cumulative strength of buffs that are not generally considered guaranteed.",
    "Strength of constant buffs": "Strength of constant buffs",
    "Cumulative strength of buffs that are generally considered guaranteed.": "Cumulative strength of buffs that are generally considered guaranteed.",
    "Number of BSs": "Number of BSs",
    "Number of building-special buffs observed in the attempt.": "Number of building-special buffs observed in the attempt.",
    "Cookie gained": "Cookie gained",
    "Total cookies gained during the attempt.": "Total cookies gained during the attempt.",
    "Handmade gain": "Handmade gain",
    "Cookies directly produced by clicks during the attempt.": "Cookies directly produced by clicks during the attempt.",
    "Initial Raw CpS": "Initial Raw CpS",
    "Baseline raw cookies-per-second at the start of the attempt.": "Baseline raw cookies-per-second at the start of the attempt.",
    "Score per Click": "Score per Click",
    "Estimated contribution to score per effective click.": "Estimated contribution to score per effective click.",
    "Score correction value": "Score correction value",
    "Automatic correction factor computed for score normalization.": "Automatic correction factor computed for score normalization.",
    "Click to activate.": "Click to activate.",
    "Click to view.": "Click to view.",
    "Click to apply this preset.": "Click to apply this preset.",
    "Click to activate. Will not invalidate score.": "Click to activate. Will not invalidate score.",
    "Click to input value.": "Click to input value.",
    "Setting value failed!": "Setting value failed!",
    "The value set was not a number!": "The value set was not a number!",
    "Click to export value.": "Click to export value.",
    "Click to input number.": "Click to input number.",
    "Click to export value.": "Click to export value.",
    "Input variable": "Input variable",
    "Please input what you want the variable to be set to.": "Please input what you want the variable to be set to.",
    "Input number": "Input number",
    "Please input a number the variable should be equal to.": "Please input a number the variable should be equal to.",
    "Export variable": "Export variable",
    "Copy the contents of the box below to export it.": "Copy the contents of the box below to export it.",
    "Input plant ages": "Input plant ages",
    "Input percentage, decimal, or words for plant stages (e.g. \"mature\" or \"budding\")": "Input percentage, decimal, or words for plant stages (e.g. \"mature\" or \"budding\")",
    "Click to input plant age.": "Click to input plant age.",
    "Click to select a value.": "Click to select a value.",
    "Select value": "Select value",
    "none": "none",
    "Random": "Random",
    "Click to select options.": "Click to select options.",
    "On": "On",
    "Off": "Off",
    "Click to toggle.": "Click to toggle.",
    "Click to hide/unhide category.": "Click to hide/unhide category.",
    "Click to make the next key press set the key.": "Click to make the next key press set the key.",
    "Press a key to set!": "Press a key to set!",
    "Key set: %1": "Key set: %1",
    "Click to open external resource in a new tab.": "Click to open external resource in a new tab.",
    "random": "random",
    "top": "top",
    "bottom": "bottom",
    "left": "left",
    "right": "right",
    "Nothing": "Nothing",
    "Building special": "Building special",
    "Building rust": "Building rust",
    "Buffs": "Buffs",
    "Buffs that will be active when you reset": "Buffs that will be active when you reset",
    "already": "already",
    "not yet": "not yet",
    "All": "All",
    "Muted": "Muted",
    "Unmuted": "Unmuted",
    "Use Elder Battalion": "Use Elder Battalion",
    "No Elder Battalion": "No Elder Battalion",
    "Rebuy": "Rebuy",
    "No rebuy": "No rebuy",
    "Add": "Add",
    "used": "used",
    "unused": "unused",
    "bought": "bought",
    "available": "available",

    //cccemInterface.js enumerable
    "Try again": "Try again",
    "Resets everything and starts another attempt.": "Resets everything and starts another attempt.",
    "Reset key select": "Reset key select",
    "Selects the key that restarts the current attempt on press.": "Selects the key that restarts the current attempt on press.",
    "(%1)": "(%1)",
    "Combo history": "Combo history",
    "The history of your combo attempts in the current session.": "The history of your combo attempts in the current session.",
    "History": "History",
    "Options group: Save/Load settings": "Options group: Save/Load settings",
    "Options related to saving and loading. ": "Options related to saving and loading. ",
    "Save/Load %1": "Save/Load %1",
    "Options group: Presets": "Options group: Presets",
    "Options related to wide-spread setting changes. ": "Options related to wide-spread setting changes. ",
    "Presets %1": "Presets %1",
    "Options group: Game settings": "Options group: Game settings",
    "Options related to the game's core features, including adjusting cookies, buildings, and lumps. ": "Options related to the game's core features, including adjusting cookies, buildings, and lumps. ",
    "Game settings options %1": "Game settings options %1",
    "Options group: Minigames": "Options group: Minigames",
    "Options related to the four minigames. ": "Options related to the four minigames. ",
    "Minigame options %1": "Minigame options %1",
    "Options group: Buffs": "Options group: Buffs",
    "Settings related to starting golden cookie buffs": "Settings related to starting golden cookie buffs",
    "Buff options %1": "Buff options %1",
    "Options group: GCs": "Options group: GCs",
    "Options related to buffs and Golden cookies. Also includes many randomness-related options.": "Options related to buffs and Golden cookies. Also includes many randomness-related options.",
    "GC options %1": "GC options %1",
    "Load P for Pause": "Load P for Pause",
    "Loads the P for Pause mod, which enables you to speed up, slow down, and stop time.": "Loads the P for Pause mod, which enables you to speed up, slow down, and stop time.",
    "Extras: P for Pause": "Extras: P for Pause",
    "Options related to the P for Pause mod. ": "Options related to the P for Pause mod. ",
    "P for Pause options %1": "P for Pause options %1",
    "Load Cast Finder": "Load Cast Finder",
    "Loads the Grimoire Cast Finder mod, which allows you to program specific strings of cast outcomes to find.<br>Disables the FtHoF button on load.": "Loads the Grimoire Cast Finder mod, which allows you to program specific strings of cast outcomes to find.<br>Disables the FtHoF button on load.",
    "Extras: Cast Finder": "Extras: Cast Finder",
    "Options related to the Cast Finder mod. ": "Options related to the Cast Finder mod. ",
    "Cast Finder options %1": "Cast Finder options %1",
    "Import Save": "Import Save",
    "Import a save of your own. Some settings will be overridden by the save's contents.": "Import a save of your own. Some settings will be overridden by the save's contents.",
    "Import save": "Import save",
    "Clear import": "Clear import",
    "Remove the currently imported save, if any.": "Remove the currently imported save, if any.",
    "Clear imported save": "Clear imported save",
    "Import settings": "Import settings",
    "Imports a setting.": "Imports a setting.",
    "Export settings": "Export settings",
    "Opens a prompt that allows you to store and reuse a setting for later.": "Opens a prompt that allows you to store and reuse a setting for later.",
    "Export save": "Export save",
    "Whether the save currently used will be exported together with settings": "Whether the save currently used will be exported together with settings",
    "%1 save": "%1 save",
    "Undo preset": "Undo preset",
    "Revert your settings to what it was before.<br>Only records the settings before the most recent preset trigger.": "Revert your settings to what it was before.<br>Only records the settings before the most recent preset trigger.",
    "Savedata container": "Savedata container",
    "You are not supposed to see this.": "You are not supposed to see this.",
    "Unlock settings": "Unlock settings",
    "Unhides other settings, for further customization of the preset.": "Unhides other settings, for further customization of the preset.",
    "Edit settings": "Edit settings",
    "Advanced mode": "Advanced mode",
    "Reveal even more buttons and customization options.": "Reveal even more buttons and customization options.",
    "Advanced mode %1": "Advanced mode %1",
    "": "",
    "Hidden option": "Hidden option",
    "M": "M",
    "Initial seed": "Initial seed",
    "Seed to determine RNG outcomes, or leave as 'R' for random. <br>Also requires either toggling on Force cast count or change FtHoF to 'random'.": "Seed to determine RNG outcomes, or leave as 'R' for random. <br>Also requires either toggling on Force cast count or change FtHoF to 'random'.",
    "Initial seed %1": "Initial seed %1",
    "Cookies": "Cookies",
    "The amount of cookies you start with each attempt.": "The amount of cookies you start with each attempt.",
    "Cookies %1": "Cookies %1",
    "Cookies Baked All Time": "Cookies Baked All Time",
    "The Cookies Baked All Time statistic. Tied to your prestige level.": "The Cookies Baked All Time statistic. Tied to your prestige level.",
    "CookiesBTA %1": "CookiesBTA %1",
    "Prestige": "Prestige",
    "Sets the amount of prestige you have.": "Sets the amount of prestige you have.",
    "Prestige %1": "Prestige %1",
    "Correction value": "Correction value",
    "The value the score should be multiplied by to better match standard values.": "The value the score should be multiplied by to better match standard values.",
    "Score mult x%1": "Score mult x%1",
    "Score correction notifications": "Score correction notifications",
    "Whether to notify when the score does not conform to the baseline.": "Whether to notify when the score does not conform to the baseline.",
    "Score info %1": "Score info %1",
    "Lumps": "Lumps",
    "The amount of Sugar lumps you start with each attempt.": "The amount of Sugar lumps you start with each attempt.",
    "Lumps %1": "Lumps %1",
    "Lump type": "Lump type",
    "The type of Sugar lump you start with each attempt.": "The type of Sugar lump you start with each attempt.",
    "Lump type %1": "Lump type %1",
    "Golden cookie click count": "Golden cookie click count",
    "The amount of all time golden cookie clicks.": "The amount of all time golden cookie clicks.",
    "%1 Golden clicks": "%1 Golden clicks",
    "Click cooldown": "Click cooldown",
    "The minimum amount of milliseconds between each click.": "The minimum amount of milliseconds between each click.",
    "Click cooldown %1ms": "Click cooldown %1ms",
    "Building count anchor": "Building count anchor",
    "The amount of Cursors you start with each attempt. Other buildings scale off this value.": "The amount of Cursors you start with each attempt. Other buildings scale off this value.",
    "Building count anchor %1": "Building count anchor %1",
    "Elder Battalion strategy": "Elder Battalion strategy",
    "Changes the building distribution to better fit an Elder Battalion strategy.": "Changes the building distribution to better fit an Elder Battalion strategy.",
    "%1": "%1",
    "Elder Battalion rebuy": "Elder Battalion rebuy",
    "Changes the building distribution to better fit a strategy rebuying after godzamok.": "Changes the building distribution to better fit a strategy rebuying after godzamok.",
    "Select building": "Select building",
    "The specific building to override or mute. Once overridden, the anchor will not affect this building.": "The specific building to override or mute. Once overridden, the anchor will not affect this building.",
    "%1:": "%1:",
    "Overriding count": "Overriding count",
    "The number of that building you start with each attempt. An assignment of 0 disables override.": "The number of that building you start with each attempt. An assignment of 0 disables override.",
    "Overriding number %1": "Overriding number %1",
    "Mute": "Mute",
    "Whether a building should start muted. Minigames will always unmute unless that option is disabled.": "Whether a building should start muted. Minigames will always unmute unless that option is disabled.",
    "Unmute minigames": "Unmute minigames",
    "Forces minigames to be unmuted on reset. If disabled, minigames can be freely muted and unmuted with the mute option.": "Forces minigames to be unmuted on reset. If disabled, minigames can be freely muted and unmuted with the mute option.",
    "Minigame %1": "Minigame %1",
    "Wizard towers": "Wizard towers",
    "The amount of Wizard towers you start with each attempt.": "The amount of Wizard towers you start with each attempt.",
    "Wizard towers %1": "Wizard towers %1",
    "Tower Level": "Tower Level",
    "The level of Wizard towers you start with each attempt.": "The level of Wizard towers you start with each attempt.",
    "Tower Level %1": "Tower Level %1",
    "Sell/Buy select": "Sell/Buy select",
    "Selects whether you are selecting 'Sell' or 'Buy' on the building list with the start of each attempt.": "Selects whether you are selecting 'Sell' or 'Buy' on the building list with the start of each attempt.",
    "Sell/Buy amount": "Sell/Buy amount",
    "Selects the bulk-buying amount you are selecting at the start of each attempt.": "Selects the bulk-buying amount you are selecting at the start of each attempt.",
    "Heralds override": "Heralds override",
    "Whether or not to override the amount of heralds to a fixed value.": "Whether or not to override the amount of heralds to a fixed value.",
    "Herald override %1": "Herald override %1",
    "Heralds": "Heralds",
    "Changes the amount of Heralds you have.<br>Max 100, usually around 100.": "Changes the amount of Heralds you have.<br>Max 100, usually around 100.",
    "Heralds %1": "Heralds %1",
    "Left Aura": "Left Aura",
    "The Dragon Aura you start with for the slot on the left.": "The Dragon Aura you start with for the slot on the left.",
    "Left Aura %1": "Left Aura %1",
    "Right Aura": "Right Aura",
    "The Dragon Aura you start with for the slot on the right.": "The Dragon Aura you start with for the slot on the right.",
    "Right Aura %1": "Right Aura %1",
    "Fortune chance": "Fortune chance",
    "The chance for a natural News ticker scroll to be a Fortune. No O fortuna: 2%. Enter in terms of percentage.": "The chance for a natural News ticker scroll to be a Fortune. No O fortuna: 2%. Enter in terms of percentage.",
    "Fortune chance: %1%": "Fortune chance: %1% ",
    "Fortune claim": "Fortune claim",
    "Whether or not the GC fortune (Today is your lucky day!) has already been claimed (and thus won't appear again).": "Whether or not the GC fortune (Today is your lucky day!) has already been claimed (and thus won't appear again).",
    "Fortune %1 claimed": "Fortune %1 claimed",
    "Starting season": "Starting season",
    "The season that you start with upon trying again.": "The season that you start with upon trying again.",
    "Starting season: %1": "Starting season: %1",
    "Scried season": "Scried season",
    "The season that the starting effect is scried (or predicted) in.": "The season that the starting effect is scried (or predicted) in.",
    "Scried season: %1": "Scried season: %1",
    "Reindeers popped": "Reindeers popped",
    "The amount of reindeers popped.": "The amount of reindeers popped.",
    "Popped %1 reindeer": "Popped %1 reindeer",
    "Elder Pledge activity": "Elder Pledge activity",
    "Whether of not Elder Pledge is active.": "Whether of not Elder Pledge is active.",
    "Elder Pledge %1": "Elder Pledge %1",
    "Record game settings in options": "Record game settings in options",
    "Makes all subsequent resets set the game settings (as in the options in the options menu) to be the options at the time of clicking.": "Makes all subsequent resets set the game settings (as in the options in the options menu) to be the options at the time of clicking.",
    "Record game settings": "Record game settings",
    "FtHoF outcome": "FtHoF outcome",
    "The outcome of the first Force the Hand of Fate cast upon starting an attempt.": "The outcome of the first Force the Hand of Fate cast upon starting an attempt.",
    "Force the Hand of Fate outcome: %1": "Force the Hand of Fate outcome: %1",
    "Force cast count": "Force cast count",
    "Forces the Grimoire's Spells casted all time stat to be whatever you choose.": "Forces the Grimoire's Spells casted all time stat to be whatever you choose.",
    "Force cast count %1": "Force cast count %1",
    "Forced cast count": "Forced cast count",
    "The value to assign to the Grimoire's Spells casted all time.": "The value to assign to the Grimoire's Spells casted all time.",
    "Forced cast count %1": "Forced cast count %1",
    "Farm Level": "Farm Level",
    "The level of your Farm, which controls the size of your garden.": "The level of your Farm, which controls the size of your garden.",
    "Farm Level %1": "Farm Level %1",
    "Holding seed": "Holding seed",
    "The seed you are holding.": "The seed you are holding.",
    "Holding %1": "Holding %1",
    "Rotation": "Rotation",
    "The orientation of the garden upon starting an attempt.": "The orientation of the garden upon starting an attempt.",
    "Rotation %1": "Rotation %1",
    "Freeze": "Freeze",
    "Whether or not the garden is frozen initially.": "Whether or not the garden is frozen initially.",
    "Garden %1": "Garden %1",
    "Tick": "Tick",
    "Progress to next tick in seconds.": "Progress to next tick in seconds.",
    "Tick %1": "Tick %1",
    "Plant 1": "Plant 1",
    "One of the plants in the garden at the start of each attempt.": "One of the plants in the garden at the start of each attempt.",
    "Plant 1 %1": "Plant 1 %1",
    "Plant 1 age": "Plant 1 age",
    "The age of the first plant at the start of each attempt.": "The age of the first plant at the start of each attempt.",
    "Plant 1 age %1": "Plant 1 age %1",
    "Ghost Tulips": "Ghost Tulips",
    "Adds ghost tulips in addition to other specified plants. Useful for starting an attempt in the middle of a combo, after you would already have replanted.": "Adds ghost tulips in addition to other specified plants. Useful for starting an attempt in the middle of a combo, after you would already have replanted.",
    "%1 Ghost Tulips": "%1 Ghost Tulips",
    "Plant 2": "Plant 2",
    "The other plant in the garden at the start of each attempt.": "The other plant in the garden at the start of each attempt.",
    "Plant 2 %1": "Plant 2 %1",
    "Plant 2 age": "Plant 2 age",
    "The age of the second plant at the start of each attempt.": "The age of the second plant at the start of each attempt.",
    "Plant 2 age %1": "Plant 2 age %1",
    "Office": "Office",
    "The Stock market Office level. The office level determines the amount of loans available.": "The Stock market Office level. The office level determines the amount of loans available.",
    "Office level %1": "Office level %1",
    "Pantheon Diamond slot": "Pantheon Diamond slot",
    "The god slotted within the Diamond slot of the Pantheon at the start of each attempt.": "The god slotted within the Diamond slot of the Pantheon at the start of each attempt.",
    "Diamond %1": "Diamond %1",
    "Pantheon Ruby slot": "Pantheon Ruby slot",
    "The god slotted within the Ruby slot of the Pantheon at the start of each attempt.": "The god slotted within the Ruby slot of the Pantheon at the start of each attempt.",
    "Ruby %1": "Ruby %1",
    "Pantheon Jade slot": "Pantheon Jade slot",
    "The god slotted within the Jade slot of the Pantheon at the start of each attempt.": "The god slotted within the Jade slot of the Pantheon at the start of each attempt.",
    "Jade %1": "Jade %1",
    "Starting buffs": "Starting buffs",
    "The buffs you will start with when you reset. Can import/export in both the format the textbox gives and the collapsed format (which saving uses)": "The buffs you will start with when you reset. Can import/export in both the format the textbox gives and the collapsed format (which saving uses)",
    "Buffs": "Buffs",
    "Snapshot": "Snapshot",
    "Will alter your starting buff settings to be the buffs you currently have active.": "Will alter your starting buff settings to be the buffs you currently have active.",
    "Snapshot buffs": "Snapshot buffs",
    "Add buff": "Add buff",
    "Which type of buff to add. BS type is selectable after cycling to building buff or building debuff.": "Which type of buff to add. BS type is selectable after cycling to building buff or building debuff.",
    "Cycle BS type": "Cycle BS type",
    "Cycle through BS types. If left at Building Buff or Building Debuff, a random one will be selected": "Cycle through BS types. If left at Building Buff or Building Debuff, a random one will be selected",
    "Cycle BS": "Cycle BS",
    "Add starting buff": "Add starting buff",
    "Will add another starting buff based on the subsequent settings (incl type, max time, time, power, BS type)": "Will add another starting buff based on the subsequent settings (incl type, max time, time, power, BS type)",
    "Confirm add %1": "Confirm add %1",
    "Maximum buff duration": "Maximum buff duration",
    "How much maximum time the added buff has, if left at 0 the buff default will be used.": "How much maximum time the added buff has, if left at 0 the buff default will be used.",
    "Max Time %1": "Max Time %1",
    "Buff duration": "Buff duration",
    "How much remaining time the added buff has, if left at 0 max time will be used.": "How much remaining time the added buff has, if left at 0 max time will be used.",
    "Time %1": "Time %1",
    "Buff power": "Buff power",
    "This is used to determine the strength of the added buff, if left at 0 the buff default will be used.": "This is used to determine the strength of the added buff, if left at 0 the buff default will be used.",
    "Power %1": "Power %1",
    "Cycle current buffs": "Cycle current buffs",
    "Will cycle through all the buffs you are starting with, so that one can be removed with the remove buff button.": "Will cycle through all the buffs you are starting with, so that one can be removed with the remove buff button.",
    "Select buff to remove": "Select buff to remove",
    "Remove starting buff": "Remove starting buff",
    "Remove one starting buff. All current starting buffs can be cycled through with the cycle remove button.": "Remove one starting buff. All current starting buffs can be cycled through with the cycle remove button.",
    "Confirm remove %1": "Confirm remove %1",
    "Clear starting buffs": "Clear starting buffs",
    "Will remove all starting buffs, making you have no buffs when resetting": "Will remove all starting buffs, making you have no buffs when resetting",
    "Clear buffs": "Clear buffs",
    "Seeded natural Golden cookies toggle": "Seeded natural Golden cookies toggle",
    "Whether naturally spawned Golden cookies will have their effects be determined by the current game seed.": "Whether naturally spawned Golden cookies will have their effects be determined by the current game seed.",
    "Seeding GC %1": "Seeding GC %1",
    "Seeded News ticker messages toggle": "Seeded News ticker messages toggle",
    "Whether Fortune appearances in the News ticker are seeded by the current game seed.": "Whether Fortune appearances in the News ticker are seeded by the current game seed.",
    "Seeding News %1": "Seeding News %1",
    "Golden switch state": "Golden switch state",
    "Whether golden switch will start on or off": "Whether golden switch will start on or off",
    "Golden Switch %1": "Golden Switch %1",
    "Initial natural Golden cookie spawn toggle": "Initial natural Golden cookie spawn toggle",
    "Whether a Golden Cookie will spawn at the start of each attempt.": "Whether a Golden Cookie will spawn at the start of each attempt.",
    "Natural GC %1": "Natural GC %1",
    "Natural spawn timer": "Natural spawn timer",
    "The amount of time after each reset for the first Golden cookie to naturally spawn (in frames, this game is 30 fps).": "The amount of time after each reset for the first Golden cookie to naturally spawn (in frames, this game is 30 fps).",
    "Nat spawn timer: %1": "Nat spawn timer: %1",
    "Initial Dragon Orbs spawn toggle": "Initial Dragon Orbs spawn toggle",
    "Whether a Golden cookie from Dragon Orbs usage will spawn at the start of each attempt.": "Whether a Golden cookie from Dragon Orbs usage will spawn at the start of each attempt.",
    "Dragon Orbs %1": "Dragon Orbs %1",
    "Initial Distilled Essence of Redoubled Luck spawn toggle": "Initial Distilled Essence of Redoubled Luck spawn toggle",
    "Whether an invoke of DEoRL at the start of each attempt will be successful.": "Whether an invoke of DEoRL at the start of each attempt will be successful.",
    "DEoRL %1": "DEoRL %1",
    "First Golden cookie effect": "First Golden cookie effect",
    "The (guaranteed) effect of the Golden cookie from the initial natural Golden cookie spawn.": "The (guaranteed) effect of the Golden cookie from the initial natural Golden cookie spawn.",
    "GC1 %1": "GC1 %1",
    "Second Golden cookie effect": "Second Golden cookie effect",
    "The (guaranteed) effect of the Golden cookie from the initial Dragon Orbs Golden cookie spawn.": "The (guaranteed) effect of the Golden cookie from the initial Dragon Orbs Golden cookie spawn.",
    "GC2 %1": "GC2 %1",
    "Third Golden cookie effect": "Third Golden cookie effect",
    "The (guaranteed) effect of the Golden cookie from the initial, successful invoke of DEoRL.": "The (guaranteed) effect of the Golden cookie from the initial, successful invoke of DEoRL.",
    "GC3 %1": "GC3 %1",
    "Sugar frenzy state": "Sugar frenzy state",
    "Whether sugar frenzy has been used before, determining whether it is available to use.": "Whether sugar frenzy has been used before, determining whether it is available to use.",
    "Sugar frenzy %1": "Sugar frenzy %1",
    "Chocolate egg purchasability": "Chocolate egg purchasability",
    "Whether chocolate egg has been purchased already, thus determining whether it can be purchased again.": "Whether chocolate egg has been purchased already, thus determining whether it can be purchased again.",
    "Chocolate egg %1": "Chocolate egg %1",
    "Dragonflight chance": "Dragonflight chance",
    "Sets a multiplier to Dragonflight (buff) chance.": "Sets a multiplier to Dragonflight (buff) chance.",
    "Dragonflight chance x%1": "Dragonflight chance x%1",
    "Golden cookie spawnrate": "Golden cookie spawnrate",
    "Sets a multiplier to the spawn rate of golden cookies.": "Sets a multiplier to the spawn rate of golden cookies.",
    "Golden cookie spawnrate x%1": "Golden cookie spawnrate x%1",
    "Save current settings": "Save current settings",
    "Saves the settings in the CCCEM interface to the save before CCCEM was loaded, as mod data.<br>You can change the saved setting by saving again.<br>You can remove it by clearing mod data with the options menu while CCCEM is not loaded.": "Saves the settings in the CCCEM interface to the save before CCCEM was loaded, as mod data.<br>You can change the saved setting by saving again.<br>You can remove it by clearing mod data with the options menu while CCCEM is not loaded.",
    "Auto Save": "Auto Save",
    "If on, the game will save CCCEM settings (identical to pressing the Save current settings button) every minute.": "If on, the game will save CCCEM settings (identical to pressing the Save current settings button) every minute.",
    "Auto save %1": "Auto save %1",
    "Building related info save": "Building related info save",
    "Saves building override and mute related information (hidden button)": "Saves building override and mute related information (hidden button)",
    "Game prefs save": "Game prefs save",
    "Saves game prefs (hidden button)": "Saves game prefs (hidden button)",
    "Active preset save": "Active preset save",
    "Saves the active preset (hidden button)": "Saves the active preset (hidden button)",
    "History settings save": "History settings save",
    "Saves the history settings (hidden button)": "Saves the history settings (hidden button)",
    "Miscellaneous save": "Miscellaneous save",
    "Saves other random stuff (hidden button)": "Saves other random stuff (hidden button)",
    "Basic combo instructions": "Basic combo instructions",
    "Click to read about doing the basic combo. It's actually really simple, trust me.": "Click to read about doing the basic combo. It's actually really simple, trust me.",
    "Guide": "Guide",
    "F + CF": "F + CF",
    "Sets the settings to one for a typical earlygame combo involving a Frenzy (shorthand F) and Click frenzy (shorthand CF).": "Sets the settings to one for a typical earlygame combo involving a Frenzy (shorthand F) and Click frenzy (shorthand CF).",
    "Basic combo": "Basic combo",
    "Combo guide": "Combo guide",
    "Opens up a combo guide for earlygame and midgame, containing more information about the subject.": "Opens up a combo guide for earlygame and midgame, containing more information about the subject.",
    "Additional info": "Additional info",
    "Endgame combo instructions": "Endgame combo instructions",
    "Opens to a specific section in a guide detailing how to do the 100% consistency, BS scry, and Grail. Setup combo is in another section of the guide.<br>The document also contains other information regarding endgame comboing.": "Opens to a specific section in a guide detailing how to do the 100% consistency, BS scry, and Grail. Setup combo is in another section of the guide.<br>The document also contains other information regarding endgame comboing.",
    "Information & Instruction": "Information & Instruction",
    "100% consistency": "100% consistency",
    "Resets settings to a preset setting for a combo with a scried Click frenzy.": "Resets settings to a preset setting for a combo with a scried Click frenzy.",
    "BS scry": "BS scry",
    "Resets settings to a preset setting for a combo with a scried Building special.": "Resets settings to a preset setting for a combo with a scried Building special.",
    "Grail": "Grail",
    "Resets settings to a preset setting for a combo with a scried Elder frenzy, which if combined with Dragonflight and Click frenzy, is called a grail.": "Resets settings to a preset setting for a combo with a scried Elder frenzy, which if combined with Dragonflight and Click frenzy, is called a grail.",
    "Setup combo": "Setup combo",
    "Resets settings to a present setting for a typical setup combo.": "Resets settings to a present setting for a typical setup combo.",
    "Browse preset": "Browse preset",
    "Browse presets in the database.": "Browse presets in the database.",
    "Find presets": "Find presets",
    "Create preset": "Create preset",
    "Create a preset to submit from your current settings, allowing anyone else to find and play on it.": "Create a preset to submit from your current settings, allowing anyone else to find and play on it.",
    "hidden button": "hidden button",
    "N": "N"
});