AddLanguage('EN', 'english', {
    "Scoring & Evaluation options %1": "Scoring & Evaluation options %1",
    "Options group: Evaluation": "Options group: Evaluation",
    "Options related to how an attempt is scored, encompassing the score and other stats.": "Options related to how an attempt is scored, encompassing the score and other stats.",
    
    "Select a tracker to get started...": "Select a tracker to get started...",
    "Select a stat to get started...": "Select a stat to get started...",
    "%1: %2": "%1: %2",
    "View watchers": "View watchers",
    "Edit stats": "Edit stats",
    "Name: %1": "Name: %1",
    "Icons": "Icons",
    "Display format": "Display format",
    "Click on the above display to edit type.": "Click on the above display to edit type.",
    "Type a number here to test the display format...": "Type a number here to test the display format...",
    "Clause #%1": "Clause #%1",
    "Miscellaneous": "Miscellaneous",
    "Cells occupied:": "Cells occupied:",
    "Displayed in notif": "Displayed in notif",
    "Displayed in history viewer": "Displayed in history viewer",

    "Click to select an icon.": "Click to select an icon.",
    "(none)": "(none)",
    "Test button %1": "Test button %1",
    "Click on an icon or its threshold to edit it. Shift-click to delete an icon.": "Click on an icon or its threshold to edit it. Shift-click to delete an icon.",
    "Click on a clause to edit it, or shift-click to delete it.": "Click on a clause to edit it, or shift-click to delete it.",
    "Input clause info": "Input clause info",
    "Change details about the clause below.": "Change details about the clause below.",
    "Text displayed when the formula matches.": "Text displayed when the formula matches.",
    "Enter text here": "Enter text here",
    "Add stat": "Add stat",
    "Delete": "Delete",
    "Are you sure?": "Are you sure?",
    "You are about to delete the item <b>%1</b>!<br>Deletion cannot be undone.": "You are about to delete the item <b>%1</b>!<br>Deletion cannot be undone.",

    "Tracker error": "Tracker error",
    "Cannot resolve all trackers due to circular dependencies. (%1 unresolved)": "Cannot resolve all trackers due to circular dependencies. (%1 unresolved)",
    "Tracker formula error": "Tracker formula error",
    "From: %1": "From: %1"
}, true);